/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ActionsCreatePostImport } from './routes/actions/create-post'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ActionsCreatePostRoute = ActionsCreatePostImport.update({
  path: '/actions/create-post',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/actions/create-post': {
      id: '/actions/create-post'
      path: '/actions/create-post'
      fullPath: '/actions/create-post'
      preLoaderRoute: typeof ActionsCreatePostImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ActionsCreatePostRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/actions/create-post"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/actions/create-post": {
      "filePath": "actions/create-post.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
